### ISSUE TITLE
LFV does not run and simply exits with code 1

### ISSUE THREAD

**Issue by jzilly** [duckietown/gym-duckietown-agent#10]
When running the LFV task, this is the output

docker-compose -f docker-compose-lfv.yml pull && docker-compose -f docker-compose-lfv.yml up 

Pulling gym-duckietown-server ... done
Pulling gym-duckietown-agent  ... done
Starting gym-duckietown-agent_gym-duckietown-server_1 ... done
Starting gym-duckietown-agent_gym-duckietown-agent_1  ... done
Attaching to gym-duckietown-agent_gym-duckietown-server_1, gym-duckietown-agent_gym-duckietown-agent_1
gym-duckietown-agent_gym-duckietown-agent_1 exited with code 1

Not really sure what is happening/not happening here.

**Comment by manfreddiaz** [comment]
Fixed in PR #11.
