### ISSUE TITLE
GL library missing

### ISSUE THREAD

**Issue by breandan** [duckietown/gym-duckietown-agent#3]
Running `docker-compose up --build` on the `master` branch fails with the following error:

```
gym-duckietown-server_1  |   File "/opt/conda/bin/duckietown-start-gym", line 11, in <module>
gym-duckietown-server_1  |   File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", lingym-duckietown-server_1  |   File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
gym-duckietown-server_1  |     return self.resolve()
gym-duckietown-server_1  |     from pyglet.gl import *
gym-duckietown-server_1  |     from pyglet.gl.lib import GLException
gym-duckietown-server_1  |   File "/opt/conda/lib/python3.6/site-packages/pyglet/gl/lib.py", line 143, ingym-duckietown-server_1  |   File "/opt/conda/lib/python3.6/site-packages/pyglet/gl/lib_glx.py", line 50, in <module>
ad_library
gym-duckietown-server_1  |     raise ImportError('Library "%s" not found.' % names[0])
```

**Comment by fgolemo** [comment]
Where does it build the server from? Because I noticed there is a new
docker/server directory in the -agent repo and i didnt update it / don't
know where it came from (because we have the same dockerfile also in the
-server repo).

**Comment by breandan** [comment]
[`gym-duckietown-agent/docker/server/Dockerfile`](https://github.com/duckietown/gym-duckietown-agent/blob/master/docker/server/Dockerfile) is a simplified version of [`gym-duckietown/docker/amod/server/Dockerfile`](https://github.com/duckietown/gym-duckietown/blob/master/docker/amod/server/Dockerfile) (I refactored and migrated it, maybe it's missing some pieces). What ever became of [this discussion](https://duckietown.slack.com/archives/C0K2VLK7D/p1531410987000239)? Did we agree to leave the Docker stuff in `duckietown/gym-duckietown` or are we planning to move everything into `gym-duckietown-agent`?

edit: The original reason for creating it was to set up the automated builder. I have deleted it now and will ask for higher permissions to `duckietown/gym-duckietown`.

**Comment by fgolemo** [comment]
I thought that would be the way to implement the results of that discussion: we have the server with its `server` container dockerfile in its own repo and the `agent` with its own dockerfile in its own repo. No crossovers.

**Comment by fgolemo** [comment]
Did I misunderstand something? Do you want all the dockerfiles in a completely different repo? Because I think `gym-duckietown-agent` is not the place for _all_ docker files.

**Comment by fgolemo** [comment]
As for the actual issue: working on it.

**Comment by breandan** [comment]
I can no longer reproduce this error. Closing.
